#!/bin/bash

test $1 != "" || {
  echo "usage: $0 file"
  echo "example: $0 single_num"
  exit 1
}

(scl -l | grep -q devtoolset-7) || {
  echo "devtoolset-7 required"
  exit 1
}

name=$(basename $1 .cc)
scl enable devtoolset-7 bash <<EOF
(g++ -o $name $name.cc -std=c++1z -g -Wall && ./$name) && {
  echo "OK"
  test -f $name && rm $name
}
EOF
